Limit the SwiftLint arguments to "--strict" and "--lenient" (#90)
* Limit the SwiftLint arguments to "strict" and "lenient"

* Add CHANGELOG item

* Implement suggestions from code review

* Replace the `if` argument check with a `while` so that the command is easier to extend

diff --git a/bin/run_swiftlint b/bin/run_swiftlint
--- a/bin/run_swiftlint
+++ b/bin/run_swiftlint
@@ -2,11 +2,29 @@
 
 echo "--- :swift: Running SwiftLint"
 
-SWIFTLINT_VERSION=$(<.swiftlint.yml awk '/^swiftlint_version: / {print $2}')
-SWIFTLINT_CMD="docker run --rm -v $PWD:/workspace -w /workspace ghcr.io/realm/swiftlint:$SWIFTLINT_VERSION swiftlint"
+SWIFTLINT_ARGUMENTS=(--quiet --reporter relative-path)
+
+while [[ "$#" -gt 0 ]]; do
+  case $1 in
+    --strict | --lenient)
+      SWIFTLINT_ARGUMENTS+=("$1")
+      shift
+      ;;
+    *) break ;;
+  esac
+done
+
+if [[ -n $1 ]]; then
+  echo "Error: invalid arguments."
+  echo "Usage: $0 [--strict | --lenient]"
+  exit 1
+fi
+
+SWIFTLINT_VERSION="$(<.swiftlint.yml awk '/^swiftlint_version: / {print $2}')"
+SWIFTLINT_DOCKER_CMD=(docker run --rm -v "$PWD":/workspace -w /workspace ghcr.io/realm/swiftlint:"$SWIFTLINT_VERSION" swiftlint)
 
 set +e
-SWIFTLINT_OUTPUT=$($SWIFTLINT_CMD lint --quiet "$@" --reporter relative-path)
+SWIFTLINT_OUTPUT=$("${SWIFTLINT_DOCKER_CMD[@]}" lint "${SWIFTLINT_ARGUMENTS[@]}")
 SWIFTLINT_EXIT_STATUS=$?
 set -e
 
